package nova.worldgen.world;

import nova.core.util.shape.Cuboid;
import nova.worldgen.ore.OreGenerationRegistry;

/**
 * This class profides information on world that world generator may need
 */
public abstract class WorldInfo {
	/**
	 * @return Size of the world, can be infinite for some directions
	 */
	public abstract Cuboid getWorldDimmensions();

	/**
	 * @return Size of chunk that is generated by world generator
	 */
	public abstract Cuboid getWorldGenerationUnitDimmensions();

	/**
	 * @return {@link OreGenerationRegistry} for the world
	 */
	public abstract OreGenerationRegistry getOreGenerationRegistry();
}
